apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: tobialaran/udagram-api-feed:v4
          imagePullPolicy: Always
          resources: {}
          envFrom: 
            - configMapRef: 
                name: env-configmap
            - secretRef:
                name: env-secret
          ports:
          - containerPort: 8080
