apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: tobialaran/udagram-frontend:v5
          imagePullPolicy: Always
          resources: {}
          ports:
          - containerPort: 80
