apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
      containers:
        - name: backend-feed
          image: tobialaran/udagram-api-feed:v10
          imagePullPolicy: Always
          resources: {}
          envFrom: 
            - configMapRef: 
                name: env-configmap
            - secretRef:
                name: env-secret
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: aws-secret
              mountPath: "/root/.aws/"
              readOnly: true
