apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: tobialaran/udagram-api-user:v10
          imagePullPolicy: Always
          resources: 
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: '1'
              memory: 1Gi
          envFrom: 
            - configMapRef: 
                name: env-configmap
            - secretRef:
                name: env-secret
          ports:
          - containerPort: 8080
