apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
        - name: reverseproxy
          image: tobialaran/reverseproxy:v5
          imagePullPolicy: Always
          resources: {}
          ports:
          - containerPort: 8080
